from __future__ import annotations

from dataclasses import dataclass
from collections.abc import Iterable

from spectra.core.types import Vec3
from spectra.core.units import CHARGE, COULOMB, NEWTON_PER_COULOMB, Quantity
from spectra.domains.mathematics.fields import VectorField3D
from spectra.domains.registry import DomainDependency, DomainRegistry


COULOMB_CONSTANT = 8.9875517923e9


@dataclass(frozen=True, slots=True)
class PointCharge:
    position: Vec3
    charge: Quantity

    def __post_init__(self) -> None:
        if self.charge.unit.dimension != CHARGE:
            raise ValueError("point charge requires an electric-charge quantity")

    @classmethod
    def coulombs(cls, position: Vec3, charge: float) -> "PointCharge":
        return cls(position=position, charge=Quantity(charge, COULOMB))


def electric_field_from_point_charges(
    charges: Iterable[PointCharge],
    *,
    singularity_radius: float = 1e-9,
) -> VectorField3D:
    """Create the SI electric field generated by stationary point charges."""
    if singularity_radius <= 0.0:
        raise ValueError("singularity_radius must be positive")

    frozen_charges = tuple(charges)

    def evaluate(position: Vec3) -> Vec3:
        field = Vec3(0.0, 0.0, 0.0)
        for charge in frozen_charges:
            displacement = position - charge.position
            radius = displacement.magnitude
            if radius < singularity_radius:
                continue
            magnitude = COULOMB_CONSTANT * charge.charge.si_value / (radius * radius)
            field = field + displacement.normalized() * magnitude
        return field

    return VectorField3D(
        evaluator=evaluate,
        name="electric_field",
        output_unit=NEWTON_PER_COULOMB,
    )


class ElectromagnetismDomain:
    name = "electromagnetism"
    version = "1"
    dependencies = (DomainDependency("mathematics.vector_field3d"),)

    def register(self, registry: DomainRegistry) -> None:
        registry.register_semantic_type("physics.electromagnetism.point_charge", PointCharge)
        registry.provide("physics.electromagnetism.point_charge", PointCharge)
        registry.provide(
            "physics.electromagnetism.electric_field_from_point_charges",
            electric_field_from_point_charges,
        )
